/* Copyright 2024 Isaac McCracken - All rights reserved
  This File is automatically generated from meta.c 
  This is an array of 64-bit unsigned integers that represent 
  all the possible moves given a position, the position is given
  by the index of the array.
  USAGE:
    #define BITMOVES_IMPLEMENTATION // define this exactly once in your program 
      // once you've defined BITMOVES_IMPLEMENTATION include this 
      #include "bitmoves.h" // after defining it once you can include it as many times as you want 
*/

#ifndef BITMOVES_H
#define BITMOVES_H

#include "types.h"

extern const U64 bitMoves[64];

#if defined(BITMOVES_IMPLEMENTATION)

const U64 bitMoves[64] = {
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu,
  0x45llu
};
#endif // #if defined(BITMOVES_IMPLEMENTATION)

#endif // BITMOVES_H