#include <stdio.h> 

typedef struct Coord {
  char x;
  char y;
} Coord;

char IndexFromCoord(Coord coord) {
  return coord.x + coord.y * 8;
}

Coord CoordFromIndex(char index) {
  return (Coord){index % 8, index / 8};
}

// this is a program that will generate a static array of all the possible konane 
// moves.
int main() {
  // Open File
  FILE *fp = fopen("bitmoves.h", "w");

  // Generate Header Comment
  fprintf(fp, "/* Copyright 2024 Isaac McCracken - All rights reserved\n");
  fprintf(fp, "  This File is automatically generated from meta.c \n");
  fprintf(fp, "  This is an array of 64-bit unsigned integers that represent \n");
  fprintf(fp, "  all the possible moves given a position, the position is given\n");
  fprintf(fp, "  by the index of the array.\n");
  fprintf(fp, "  USAGE:\n    #define BITMOVES_IMPLEMENTATION // define this exactly once in your program \n");
  fprintf(fp, "      // once you've defined BITMOVES_IMPLEMENTATION include this \n");
  fprintf(fp, "      #include \"bitmoves.h\" // after defining it once you can include it as many times as you want \n");

  fprintf(fp, "*/\n\n");



  // Generate Header Guard
  fprintf(fp, "#ifndef BITMOVES_H\n#define BITMOVES_H\n\n");

  fprintf(fp, "#include \"types.h\"\n\n");

  fprintf(fp, "extern const U64 bitMoves[64];\n\n");

  fprintf(fp, "#if defined(BITMOVES_IMPLEMENTATION)\n\n");

  /*
    if This is our position:
      0 0 0 0 0 0 0 0 
      0 0 0 0 0 0 0 0 
      0 0 0 0 0 0 0 0 
      0 0 0 0 X 0 0 0 
      0 0 0 0 0 0 0 0 
      0 0 0 0 0 0 0 0 
      0 0 0 0 0 0 0 0 
      0 0 0 0 0 0 0 0 
    then our moves would be possible moves:
      0 0 0 0 0 0 0 0  
      0 0 0 0 x 0 0 0 
      0 0 0 0 0 0 0 0 
      x 0 x 0 - 0 x 0 
      0 0 0 0 0 0 0 0 
      0 0 0 0 x 0 0 0 
      0 0 0 0 0 0 0 0 
      0 0 0 0 x 0 0 0 
  */

  fprintf(fp, "const U64 bitMoves[64] = {\n");
  for (char i = 0; i < 64; i++) {
    unsigned long long result = 0;
    char grid[64] = { 0 };
    Coord coord = CoordFromIndex(i);

    // right
    for (char x = coord.x; x < 8; x += 2)
      grid[IndexFromCoord((Coord){x, coord.y})] = 1;
    // left
    for (char x = coord.x; x >= 0; x -= 2)
      grid[IndexFromCoord((Coord){x, coord.y})] = 1;
    // up 
    for (char y = coord.y; y >= 0; y -= 2)
      grid[IndexFromCoord((Coord){coord.x, y})] = 1;
    for (char y = coord.y; y >= 0; y -= 2)
      grid[IndexFromCoord((Coord){coord.x, y})] = 1;
    

    fprintf(fp, "  0x%xllu", 69);

    if (i < 63) putc(',', fp);
    putc('\n', fp);

  }
  fprintf(fp, "};\n");
  


  fprintf(fp, "#endif // #if defined(BITMOVES_IMPLEMENTATION)\n\n");
  // Generate Header Guard end
  fprintf(fp, "#endif // BITMOVES_H");

  // Close File
  fclose(fp);
}